# Generated by Django 5.1.7 on 2025-03-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='strategy',
            field=models.CharField(choices=[('long/short equity', 'Long/Short Equity'), ('global macro', 'Global Macro'), ('arbitrage', 'Arbitrage')], max_length=20, verbose_name='Strategy'),
        ),
    ]
